### ISSUE TITLE
Inconsistent Schema in Task

### ISSUE THREAD

**Issue by biomousavi** [litus-ai/full-stack-interview#1]
Hey, I noticed the schema says we need a 'creation_time' field and no 'description', but the sample data includes 'description' and is missing 'creation_time'.  2ab634e333b10f02092513947280db9364853521 and 657921d9b2da5ca92495feb412ad80b2b9ca6520

**Can we get them aligned?** Either update the schema or the sample data so they match. Thanks

**Comment by poccio** [comment]
Hey there, nice catch, just pushed a commit that fixes it (removing description and setting creation_time in the sample data)
